name: json_compress
description: Json Compression
version: 1.0.8
homepage: https://github.com/ArcaneArts/json_compress
environment:
  sdk: '>=2.18.6 <4.0.0'
dependencies:
  jpatch: ^1.0.1
  threshold: ^1.0.4
dev_dependencies:
  test: ^1.24.4
